In [2]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.23496994 0.65868406 0.15611448]
  [0.39301176 0.64874339 0.94423213]
  [0.72734862 0.57704233 0.7942513 ]]

 [[0.70137511 0.29104261 0.64315527]
  [0.8048432  0.14520033 0.10065827]
  [0.10051592 0.68080361 0.25479146]]

 [[0.81373026 0.58705603 0.26163638]
  [0.35141693 0.3638101  0.5606498 ]
  [0.00128513 0.70826375 0.11320304]]]


In [3]:
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [4]:
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [5]:
x= np.random.random((3,3))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.31495964 0.96051897 0.43705827]
 [0.20775093 0.6765146  0.69780803]
 [0.09090475 0.11795116 0.26507552]]
After normalization:
[[0.25764861 1.         0.39805411]
 [0.13436554 0.67341338 0.69789945]
 [0.         0.03110162 0.2002851 ]]


In [6]:
array1 = np.array([0, 10, 20, 40, 70])
print("Array1: ",array1)
array2 = [10, 30, 40,70]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 70]
Array2:  [10, 30, 40, 70]
Common values between two arrays:
[10 40 70]


In [7]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-24
Today:  2020-07-25
Tomorrow:  2020-07-26


In [8]:
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[1 0 1 0 1 0]
Second array:
[0 1 0 1 1 0]
Test above two arrays are equal or not!
False


In [9]:
x = np.random.random(15)
print("Original array:")
print(x)
x[x.argmax()] = -1
print("Maximum value replaced by -1:")
print(x)

Original array:
[0.91101835 0.76145418 0.289275   0.47455723 0.73100417 0.03549279
 0.66924668 0.36500354 0.57649139 0.31541642 0.80830153 0.13762536
 0.87625478 0.75368296 0.24539463]
Maximum value replaced by -1:
[-1.          0.76145418  0.289275    0.47455723  0.73100417  0.03549279
  0.66924668  0.36500354  0.57649139  0.31541642  0.80830153  0.13762536
  0.87625478  0.75368296  0.24539463]


In [10]:
np.set_printoptions(threshold=np.inf)
x = np.zeros((4, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.04515037 0.77752427 0.01341928 0.77732649 0.93534346 0.68763052
  0.93857467 0.05693786 0.37656511 0.33414564]
 [0.04945211 0.01793002 0.82013736 0.43219898 0.05357706 0.52471667
  0.37808954 0.62807853 0.03137933 0.73536342]
 [0.543406   0.25446201 0.48371163 0.66861    0.5158191  0.36982498
  0.16300928 0.21676584 0.14257994 0.58143413]
 [0.16642051 0.48689209 0.29129848 0.01586036 0.60335391 0.05191682
  0.80710554 0.2908361  0.60569661 0.45745967]
 [0.70769299 0.78574215 0.15799783 0.93135791 0.56350889 0.96621526
  0.41181853 0.38652382 0.6190165  0.0682778 ]]

Subtract the mean of each row of the said matrix:

[[-0.4491114   0.2832625  -0.48084249  0.28306473  0.44108169  0.19336875
   0.4443129  -0.43732391 -0.11769665 -0.16011613]
 [-0.31764019 -0.34916228  0.45304506  0.06510668 -0.31351524  0.15762437
   0.01099724  0.26098622 -0.33571297  0.36827111]
 [ 0.14944371 -0.13950029  0.08974934  0.27464771  0.12185681 -0.02413731
  -0.23095301 -0.17719645 -0.2

In [12]:
a1=np.array([1,2,3,4])
a2=np.array(['Red','Green','White','Orange'])
a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')
print(result[0])
print(result[1])
print(result[2])


(1, 'Red', 12.2)
(2, 'Green', 15.)
(3, 'White', 20.)


In [13]:
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]


In [14]:
x = np.random.randint(0, 10, 40)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[6 9 7 6 4 5 6 7 0 5 3 7 6 7 2 2 4 9 7 4 9 1 9 6 3 2 0 5 0 9 3 7 9 8 8 6 3
 4 0 6]
Most frequent value in the above array:
6


In [16]:
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))
np.diag(np.dot(A, B))
np.sum(A * B.T, axis=1)
np.einsum("ij,ji->i", A, B)

array([ 36, 128,  82])

In [17]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[5. 3. 1. 2. 5. 3. 3. 1. 2. 5.]
